name: recetario_vertex_ai
description: "Recetario con Vertex AI"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.6.0
  firebase_vertexai: ^0.1.0
  image_picker: ^1.0.4
  flutter_dotenv: ^5.0.2
  http: ^1.1.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/
